### ISSUE TITLE
Training & Travel Request: Look into sending links in notification emails rather than document attachment

### ISSUE THREAD

**Issue by gjoverto** [City-of-Bloomington/onbase#8]

**Comment by inghamn** [comment]
Currently, the only link in the notification emails is to the Workflow  in the web client.  A PDF of the Travel Request is generated and attached.  

One issue with  only linking to the Workflow is that Workflow provides no mechanism to get over to Document Retrieval, which users are frequently asking for.   Well, not in so many words....they are asking how they can view the past Travel Requests; and the only link they ever get is the link to the Workflow....and you can't get to Document Retrieval from there.

It would be good to include a link to the Travel Request in Document Retrieval, instead of attaching a PDF to the email notification.  That way, staff know the URL to get to Document Retrieval.  This would also keep the size of the email notifications down and, hopefully, simplify the Workflow actions.
